events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://web-frontend-server;
    }

    location /api/ {
      rewrite ^/api/(.*)$ /$1 break;
      proxy_pass http://application-backend-server:8081;
    }
  }
}